# version: '3.4'
services:
  mariadb:
    image: mariadb:10.3
    container_name: barabbas-db
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: testpass
    volumes:
      - ./EN15907.sql:/docker-entrypoint-initdb.d/EN15907.sql
  api:
    image: barabbas-api
    container_name: barabbas-api
    restart: always
    ports:
      - "5000:5000"
