
FROM python:3.11-alpine

RUN apk update && apk add mariadb-dev gcc musl-dev

WORKDIR /flask

COPY . /flask

RUN ls -al

RUN pip install -r requirements.txt

RUN mv api.py app.py

CMD [ "gunicorn", "-w", "4", "-b", "0.0.0.0:5000", "app:app"]